### ISSUE TITLE
PHP Fatal error: mysqli object already closed in Hotel Management System

### ISSUE THREAD

**Issue by Josaphat12-tech** [tushar-2223/Hotel-Management-System#8]
Description:
While working on my Hotel Management System project, I encountered the following error in the Apache error log:
`[Wed Apr 10 17:28:29.126727 2024] [php:error] [pid 15690] [client 127.0.0.1:53152] PHP Fatal error:  Uncaught Error: mysqli object is already closed in /var/www/html/Hotel-Management-System/index.php:10\nStack trace:\n#0 /var/www/html/Hotel-Management-System/index.php(10): mysqli_query()\n#1 {main}\n  thrown in /var/www/html/Hotel-Management-System/index.php on line 10, referer: http://localhost/Hotel-Management-System/
`
This error indicates that the mysqli object is already closed at line 10 of my index.php file. Here's the corresponding stack trace:

`#0 /var/www/html/Hotel-Management-System/index.php(10): mysqli_query()
#1 {main}
`
It seems to be causing issues with the functionality of my application, particularly in the database interaction part. I've tried troubleshooting it, but I'm unable to pinpoint the exact cause.

If anyone has encountered a similar issue or has insights on how to resolve this, I would greatly appreciate your assistance. Thank you!

**Comment by Josaphat12-tech** [comment]
please help me solve this guys !!!

**Comment by Ruhan58** [comment]
The requested URL was not found on this server.

Apache/2.4.58 (Win64) OpenSSL/3.1.3 PHP/8.2.12 Server at localhost Port 80
